type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type Parcel @table {
  parcelID: String! # parcelID is unique but Data Connect implicitly adds an 'id: UUID!' field that is unique and the primary key.
  address: String!
  latitude: Float!
  longitude: Float!
  areaSqM: Float!
  createdAt: Timestamp!
  legalDescription: String
  zoning: String
  currentOwnerName: String
  lastSaleDate: Date
  lastSalePrice: Float
}

type OwnershipHistory @table {
  parcel: Parcel!
  ownerName: String!
  transferDate: Date!
  transferType: String
  price: Float
}

type ZoningRegulation @table {
  parcel: Parcel!
  zoningType: String!
  allowedUses: String!
  createdAt: Timestamp!
  heightRestrictions: String
  setbackRequirements: String
}

type Watchlist @table {
  user: User!
  name: String!
  createdAt: Timestamp!
  description: String
}

type WatchlistItem @table(key: ["watchlist", "parcel"]) {
  watchlist: Watchlist!
  parcel: Parcel!
  addedAt: Timestamp!
  notes: String
}